apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-image
  template:
    metadata:
      labels:
        app: redis-image
    spec:
      containers:
      - name: redis-image
        image: redis:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-storage
        emptyDir: {}
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-image
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
