apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-image
  template:
    metadata:
      labels:
        app: voting-image
    spec:
      containers:
      - name: voting-image
        image: devops-voting-app-vote
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: Never
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  selector:
    app: voting-image
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31000

