name: Test and Build
on:
  push:
    branches:
      - feature/local-k8s
  pull_request:
    branches:
      - feature/local-k8s

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: set the docker repo name 
        run: echo "REPO=$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - name: build images
        run: |
          chmod +x ./image-build.sh
          ./image-build.sh
      - name: List Docker images
        run: docker images
      
      