name: Test and Build
on:
  push:
    branches:
      - feature/local-k8s
  pull_request:
    branches:
      - feature/local-k8s

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: set the docker repo name 
        run: echo "REPO=$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - name: build images
        run: |
          chmod +x ./image-build.sh
          ./image-build.sh
      - name: List Docker images
        run: docker images
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1
      - name: Push to Amazon ECR
        run: | 
          docker push $REPO/results-app:latest
          docker push $REPO/voting-app:latest
          docker push $REPO/worker-app:latest