name: Test and Build
on:
  push:
    branches:
      - feature/local-k8s
  pull_request:
    branches:
      - feature/local-k8s

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: set the docker repo name 
        run: echo "REPO=195162992068.dkr.ecr.us-east-1.amazonaws.com" >> $GITHUB_ENV
      - name: build images
        run: |
          chmod +x ./image-build.sh
          ./image-build.sh
      - name: List Docker images
        run: docker images
      
      