name: Test and Build
on:
  push:
    branches:
      - feature/local-k8s
  pull_request:
    branches:
      - feature/local-k8s
  workflow_dispatch:
    inputs: 
      version:
        description: 'Version to build'
        required: true
        default: 'v1.0.0'

    

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: set the docker repo name 
        run: echo "REPO=195162992068.dkr.ecr.us-east-1.amazonaws.com" >> $GITHUB_ENV
      - name: build images
        run: |
          chmod +x ./image-build.sh
          ./image-build.sh
      - name: List Docker images
        run: docker images

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push to Amazon ECR
        run: |
          docker tag "$REPO"/results-app:latest "$REPO"/results-app:${{ inputs.version != '' && inputs.version || github.sha }}
          docker tag "$REPO"/voting-app:latest "$REPO"/voting-app:${{ inputs.version != '' && inputs.version || github.sha }}
          docker tag "$REPO"/worker-app:latest "$REPO"/worker-app:${{ inputs.version != '' && inputs.version || github.sha }}
          docker push "$REPO"/results-app:${{ inputs.version != '' && inputs.version || github.sha }}
          docker push "$REPO"/voting-app:${{ inputs.version != '' && inputs.version || github.sha }}
          docker push "$REPO"/worker-app:${{ inputs.version != '' && inputs.version || github.sha }}
      
      
      